require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Ajyal' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'AjyalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.74.0'}) # should match the version of your Flipper client app
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Ajyal-tvOS' do
  # Pods for Ajyal-tvOS

  target 'Ajyal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
